### ISSUE TITLE
Not working with ERPNext 14 - PLEASE FIX🙋‍♂️

### ISSUE THREAD

**Issue by thekingchild** [MohammadAhmad1990/erpnext_quota#15]
Hello, thanks for giving us this ERPNext app. Unfortunately, it doesn't work with ERPNext v14. 
Kindly update to fix this issue.

Regards

**Comment by ahmadpak** [comment]
@femijoshuao Hey Thank you. Can you share any errors?

**Comment by ahmadpak** [comment]
@femijoshuao please try again now

**Comment by ahmadpak** [comment]
with version-14 branch
