### ISSUE TITLE
Giving Internal Server Error on ERPNEXT 14

### ISSUE THREAD

**Issue by Fakhru2209** [MohammadAhmad1990/erpnext_quota#16]
Internal Server Error giving this error on erpnext 14

Please update the code to use it.

**Comment by ahmadpak** [comment]
@Fakhru2209 when are you facing this issue?

**Comment by Fakhru2209** [comment]
I have installed it on one of my site now its giving this error "internal server error"


I tried to uninstall and delete but none is working. Couldn't restore back ERPNEXT.

**Comment by ahmadpak** [comment]
@Fakhru2209 check bench logs folder for the information on why it is failing to start

**Comment by ahmadpak** [comment]
@Fakhru2209 Can you try again now
