### ISSUE TITLE
Error 500: internal server error on v14

### ISSUE THREAD

**Issue by OneSpaceerp** [MohammadAhmad1990/erpnext_quota#18]
hello Ahmad
First of all many thanks for the great work, I installed the app on erpnext v14 its worked fine in limiting users and dates, but when I try to upload an image or file to any module I face Error 500 internal server error.

**Comment by OneSpaceerp** [comment]
Any update

**Comment by ahmadpak** [comment]
@OneSpaceerp Thank you for the appreciation. Can you please share the error log

**Comment by OneSpaceerp** [comment]
![500](https://user-images.githubusercontent.com/118968197/208434928-fe1600e5-9b23-42b3-a86c-f0b532971767.png)

**Comment by OneSpaceerp** [comment]
![site_config](https://user-images.githubusercontent.com/118968197/208434976-44c8058f-bc15-40dd-a3ae-f07492dd7211.png)

**Comment by OneSpaceerp** [comment]
Hellow ahmed
Any updates

**Comment by OneSpaceerp** [comment]
Hellow Ahmed
Any updates

**Comment by ahmadpak** [comment]
@OneSpaceerp fixed for 

1. develop
2. version-14
