### ISSUE TITLE
Feature Request: Sales Invoices Limit

### ISSUE THREAD

**Issue by 0FiRE0** [MohammadAhmad1990/erpnext_quota#20]
Thank you for the good work.

Can you please add a new limit for the number of Sales Invoices to be created.

E.g. Limiting the total number of Sales Invoices to be 100, after that it will ask the user to check with the Administrator to increase the limit.

Or we can make this new field dynamic so that the Administrator can select any Doc Type and set the limit for it.

**Comment by ahmadpak** [comment]
Than you. Sure I can do that. Swamped in work now a days. Will try to update asap

**Comment by mymi14s** [comment]
@ahmadpak if this feature request will add value, I can work on it.

**Comment by ahmadpak** [comment]
@mymi14s sure feel free to contribute

**Comment by mymi14s** [comment]
@ahmadpak @0FiRE0 contribution made, PR raised https://github.com/ahmadpak/erpnext_quota/pull/21
The PR is not limited to sales invoice but any other doctype.

**Comment by thekingchild** [comment]
**Thanks so much for these contributions.**  This project has been helpful.  Don't forget to fix reported issues on social media logins error, report generation, and passwords. I **think** they are related to the permission bugs.

**Comment by 0FiRE0** [comment]
> @ahmadpak @0FiRE0 contribution made, PR raised #21 The PR is not limited to sales invoice but any other doctype.

Thank you so much @mymi14s for your support.

**Comment by ahmadpak** [comment]
@mymi14s Thank you for the contribution. @femijoshuao @0FiRE0 The feature has been deployed 🎉

**Comment by mymi14s** [comment]
@ahmadpak you are highly welcome
