### ISSUE TITLE
Users Allowed 0 and users are still able to do SI, SO, Qnt ...

### ISSUE THREAD

**Issue by Helkyd** [MohammadAhmad1990/erpnext_quota#3]
Hi,
If i have Users allowed 0 should not allow besides the ADMINISTRATOR (System Manager) to login and do SI,SO, etc....

![image](https://user-images.githubusercontent.com/20396898/102249240-6f9d5b00-3f02-11eb-86c6-51f766ee1006.png)

Can you fix that if Users Allowed 0 no docs are allowed to create like main ones (SI,QNT,SO,JV,etc) for companies to work.

**Comment by ahmadpak** [comment]
@Helkyd at least 1 User is required as System manager. So having zero Allowed users does not make much sense.
The 1st User is create automatically during the signup process.

**Comment by ahmadpak** [comment]
@Helkyd More over the user validation is while creating the User not on specific documents. That depends on the space allowed for the DB. If DB space limit is exceeded it will still allow you to save the document but will not allow to submit them. Please review the latest documentation

**Comment by Helkyd** [comment]
Thanks for the updates.
Will update the app and test.
