### ISSUE TITLE
User count

### ISSUE THREAD

**Issue by ryuliantoro** [MohammadAhmad1990/erpnext_quota#8]
Currently your user count filters in install.py is still counting Administrator.
```
filters = {
    'enabled': 1,
    'name': ['!=','Guest', 'Administrator']
  }
```
It only takes the `'!=', 'Guest'` and ignore the `'!=', 'Administrator'` hence the user count also includes Administrator.

It should be
```
  filters = [
    {'enabled': 1}, 
    {'name': ['!=','Administrator']}, 
    {'name': ['!=','Guest']}
  ]
```

**Comment by ahmadpak** [comment]
@ryuliantoro This is fixed.
`  filters = {
    'enabled': 1,
    'name': ['not in',['Guest', 'Administrator']]
  }`
